name: release

on: push
#on:
#  release:
#    types:
#      - created

jobs:
  linux:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: true

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'

      - name: Restore PHP build cache
        id: php-build-cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/php
          key: php-8.0.19

      - name: Clone php-build repository
        if: steps.php-build-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          repository: php-build/php-build
          path: php-build

      - name: Compile PHP
        if: steps.php-build-cache.outputs.cache-hit != 'true'
        run: |
          ./install-dependencies.sh
          PHP_BUILD_ZTS_ENABLE=on ./bin/php-build 8.0.19 $GITHUB_WORKSPACE/php
        working-directory: php-build

      - name: Dump PHP info
        run: $GITHUB_WORKSPACE/php/bin/php -i

      - name: Build extension
        run: |
          $GITHUB_WORKSPACE/php/bin/phpize
          ./configure --with-php-config=$GITHUB_WORKSPACE/php/bin/php-config --enable-calljava
          make install
        working-directory: extension

      #- name: Upload a Release Asset
        #uses: shogo82148/actions-upload-release-asset@v1
        #with:
          #upload_url: ${{ github.event.release.upload_url }}
          #asset_path: ${{ github.workspace }}/extension/modules/calljava.so

      - name: Compile Loader
        run: |
          ./gradlew setupMinecraft
          ./gradlew :reobf:shadowjar
        working-directory: JELoader

      #- name: Upload a Release Asset
        #uses: shogo82148/actions-upload-release-asset@v1
        #with:
          #upload_url: ${{ github.event.release.upload_url }}
          #asset_path: ${{ github.workspace }}/JELoader/reobf/build/libs/*.jar
          #asset_name: JELoader

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: windows
          path: |
            ${{ github.workspace }}/extension/modules/calljava.so
            ${{ github.workspace }}/JELoader/reobf/build/libs/*.jar
          if-no-files-found: error

  windows:
    runs-on: windows-2019
    
    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: true

      - name: Install tools and dependencies
        run: choco install wget --no-progress

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'

      - name: Set bot email
        run: git config --global user.email "action@github.com"
        
      - name: Set bot name
        run: git config --global user.name "GitHub Action"

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: build-script

      - name: Apply patches
        run: ./gradlew applypatches
        working-directory: build-script

      - name: Compile PHP
        run: .\windows-compile-vs.bat
        env:
          VS_EDITION: Enterprise
          SOURCES_PATH: ${{ github.workspace }}\pocketmine-php-sdk
        working-directory: build-script/build-script

      - name: ls
        run: ls
        working-directory: build-script/build-script

      #- name: Upload a Release Asset
        #uses: shogo82148/actions-upload-release-asset@v1
        #with:
          #upload_url: ${{ github.event.release.upload_url }}
          #asset_path: ${{ github.workspace }}/build-script/build-script/bin/php/ext/php_calljava.dll

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: windows
          path: ${{ github.workspace }}/build-script/build-script/bin/php/ext/php_calljava.dll
          if-no-files-found: error
